feat(githooks): implement changed modules verification
- Implement verification to detect the affected modules by a commit.
- Now, only the necessary ones are recompiled, optimizing the hook execution.
- Add colors to the first and last message printed in the terminal
- Minor formatting changes

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,23 +1,70 @@
 #!/bin/bash
 
-echo "--------------------------------------------------------"
-echo "🚧 Verifying build integrity before the commit..."
-echo "--------------------------------------------------------"
+echo -e "\e[33m------------------------------------------------\e[0m"
+echo -e "\e[33m Verifying build integrity before the commit...\e[0m"
+echo -e "\e[33m------------------------------------------------\e[0m\n"
 
-# -B: Batch mode (less colorful/interactive logs)
-# -q: Quiet (prints only errors)
-./mvnw -f ./apps/pom.xml clean compile -B -q
+STAGED_FILES=$(git diff --name-only --cached --diff-filter=d) # All files include, except the deleted ones
+
+if [ -z "$STAGED_FILES" ]; then
+  exit 0
+fi
+
+MODULES=""
+MODULES_ROOT="../apps"
+
+for file in "${STAGED_FILES[@]}"; do
+  if [ "$file" = "$MODULES_ROOT/pom.xml" ]; then
+      MODULES="ALL"
+      break
+  fi
+
+  DIR=$(echo "$file" | cut -d'/' -f2)
+
+  if [ -f "$MODULES_ROOT/$DIR/pom.xml" ]; then
+    case "$MODULES" in
+      *"$DIR"*)
+        ;;
+
+      *)
+        if [ -z "$MODULES" ]; then
+          MODULES="$DIR"
+        else
+          MODULES="$MODULES,$DIR"
+        fi
+        ;;
+    esac
+  fi
+done
+
+if [ -n "$MODULES" ]; then
+  echo "Changes detected in the modules: $MODULES"
+  echo "Recompiling them..."
+  ../mvnw -f "$MODULES_ROOT/pom.xml" clean compile -pl "$MODULES" -am -B
+
+elif [ "$MODULES" = "ALL" ]; then
+  echo "Changes detected on parent pom.xml"
+  echo "Recompiling the entire project..."
+  ../mvnw -f "$MODULES_ROOT/pom.xml" clean compile -B
+
+else
+  echo -e "\n\e[32m-----------------------------------------------\e[0m"
+  echo -e "\e[32mNo modules changed. Proceeding with the commit.\e[0m"
+  echo -e "\e[32m-----------------------------------------------\e[0m"
+  exit 0
+fi
 
 EXIT_CODE=$?
 
 if [ $EXIT_CODE -ne 0 ]; then
-    echo " "
-    echo "❌ ABORTING THE COMMIT!"
-    echo "The project does not compile. Correct the errors and try again."
-    echo "--------------------------------------------------------"
-    exit 1
+  echo -e "\n\e[33m---------------------------------------------------------------\e[0m"
+  echo -e "\e[33m ABORTING THE COMMIT!\e[0m"
+  echo -e "\e[33mThe project does not compile. Correct the errors and try again.\e[0m"
+  echo -e "\e[33m---------------------------------------------------------------\e[0m"
+  exit 1
 else
-    echo "✅ Approved compile. Proceeding with the commit."
-    echo "--------------------------------------------------------"
-    exit 0
+  echo -e "\n\e[32m-----------------------------------------------\e[0m"
+  echo -e "\e[32m Approved compile. Proceeding with the commit.\e[0m"
+  echo -e "\e[32m-----------------------------------------------\e[0m"
+  exit 0
 fi
